openapi: 3.0.1
info:
  #contact:
  #email: documentsupport@paynearby.in
  #name: Document Support
  #url: https://nearby.documentservice.com
  description: |
    # Introduction
    Document Generator API allows you easily generate PDF documents and reduce the development and support costs by enabling your users to create and manage their document templates.
    ## Base URL
    The base URL for all the API endpoints is `https://services-aepsv2-uat.paynearby.in/api/v1`
    For example
    * `https://services-aepsv2-uat.paynearby.in/api/v1/templates`
    * `https://services-aepsv2-uat.paynearby.in/api/v1/documents/{templateId}`
    # Error codes
    | Code   | Description                    |
    |--------|--------------------------------|
    | 401    | Unauthorized                   |
    | 403    | Forbidden                      |
    | 404    | Not Found                      |
    | 409    | Conflict                       |
    | 422    | Unprocessable Entity           |
    | 500    | Internal Server Error          |
  title: Document Generator API
  version: 3.1.1
servers:
  - url: https://nearby.documentservice.com/api/v1
tags:
  - name: Templates
    description: Register & Unregister Templates.
  - name: Document
    description: Generate Document
paths:
  /documents:
    post:
      tags:
        - Document
      description: Generate Document, document content must be sent in the request body.
      operationId: register-template
      parameters:
        - name: templateId
          in: query
          required: true
          schema:
            type: string
        - name: appId
          in: query
          required: true
          schema:
            type: string
        - name: docType
          in: query
          required: false
          schema:
            type: string
            default: PDF
            enum:
              - PDF
              - DOCX
              - PNG
              - OTHER
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentDetails'
        required: true
      responses:
        "201":
          description: Document created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
              examples:
                Template created:
                  description: Template created
                  value:
                    data: "JVBERi0xLjQKJfbk/N8KMSAwIG9iago8PAovVHlwZSAvQ2F0YWxvZwovVmVyc2lvbiAvMS43Ci9QYWdlcyAyIDAgUgo+PgplbmRvYmoKMyAwIG9iago8PAovQ3JlYXRpb25EYXRlIChEOjIwMjIwNjAyMTYwNjQwKzA1JzMwJykKL1Byb2R1Y2VyIChvcGVuaHRtbHRvcGRmLmNvbSkKL1RpdGxlIChUcmFuc2FjdGlvbiBSZWNlaXB0KQo+PgplbmRvYmoKMiAwIG9iago8PAovVHlwZSAvUGFnZXMKL0tpZHMgWzQgMCBSXQovQ291bnQgMQo+PgplbmRvYmoKNCAwIG9iago8PAovVHlwZSAvUGFnZQovTWVkaWFCb3ggWzAuMCAwLjAgNTk1LjI3NSA4NDEuODc1XQovUGFyZW50IDIgMCBSCi9Db250ZW50cyA1IDAgUgovUmVzb3VyY2VzIDYgMCBSCj4+CmVuZG9iago1IDAgb2JqCjw8Ci9MZW5ndGggNjQzCi9GaWx0ZXIgL0ZsYXRlRGVjb2RlCj4+CnN0cmVhbQ0KeJydVstu2zAQvPMr9lQkhzDLN5VbbMeAC9hoYhU9ND0oClMrtaTWllPk70M5fkiNYdGF4QMJzgx3huQKKQqj4C/h8JkgPBOGMCbffwDCI/lDhAaLilq/JCdKRZQbhXw3N2/MCV1TSesnPao92q+fkW+k8MTaUOU1ELimXIEWYJSkKKMogjQnl6OcwaAktwTXqxY/SS8ml0MGzEL8RNh61o8EB2MY5VENjHNyFi+SYpmkVVYWcA7xM7mJj0BlRK3XtGvonUtd9rvaopBy2P4b+sJvvEGjlB/rSNPaxpqlv1pWZe4WMHBVks2XVzu+ViUcGG/xGNBGUuVt4muecfmQzR1MVvmDJ2uVcgirkRrGN9j7s+l4en9+FMQsX6sxjzVUK8R3bIRSMq61wE5NEVEhtvvd1T1Jcheq3GK4fimy5ew/7FfG0IhxaT+cgJMzUEpTb+MHommVVKtlYFlNkkFZHHejFhWSmo+ao0Go3h7PuJBKGxt1anonxQHRQVI5+NR53vyloRtwFhx3U5PbC1QXHLlP2FyhvQrk2Atj5wGVxu5y+JK85q6oYOyqWfkYKtYg6Cez4/nXgj74A56Oy8dQixoMk5th3Cko1MEUO3GcbVy8zstVUYXujlsqdwkGBIC4968sXlyRuSJ1MHTBfjQYkCLvUhQ+sa0fZZXM4aT6GuhGdSe8REIwyqJtQ+n5ep+yNEsWr6e/RAIjKnePWpPqhAe2TXKXPHf5x63dNO5/VXtJ8StQtU0y7Y06VbWmWh+q9TpN6/w6D7TvfNRY38/fr866aYbu1n/CGC43mQnkm1+npM+69vZdsrYHRsNpH/rht71N4Y36OqmlxRZ+S94AAwkiaA0KZW5kc3RyZWFtCmVuZG9iago2IDAgb2JqCjw8Ci9YT2JqZWN0IDw8Ci9JbTEgNyAwIFIKPj4KL0ZvbnQgOCAwIFIKPj4KZW5kb2JqCjcgMCBvYmoKPDwKL0xlbmd0aCAyNTM3Ci9UeXBlIC9YT2JqZWN0Ci9TdWJ0eXBlIC9JbWFnZQovRmlsdGVyIC9GbGF0ZURlY29kZQovQml0c1BlckNvbXBvbmVudCA4Ci9XaWR0aCAxNDgKL0hlaWdodCA1OQovQ29sb3JTcGFjZSAvRGV2aWNlUkdCCi9EZWNvZGVQYXJtcyA5IDAgUgovU01hc2sgMTAgMCBSCi9JbnRlcnBvbGF0ZSB0cnVlCj4+CnN0cmVhbQ0KeJztW/lzE+cZlnallVb37QNjjMFxgQDGB2AmtOZKk+mkM7RJGNofmvbXpmmnf0iPmU5/y0yboS0NAUpIyAHYJrEpgRo7xoCNMbZjfEu2jtWxWu1un9V2GBpsWYcteZl98AyyLK2+73ve93mf99tPWlEUNSqUCS3IKz/+l1zfFgpYDv24Z++xe8F56xqM6vmH3R29e7Pms1P7TbaEVptP/sycf4vI77MFnqDNrIFO4kF+V1BROPJcetB2/z81kUWzzRVV+SsV8lx3iz3+sL/q7J8PpTiStiREUbu6w1KRDfKVTUHrLg8Nf1116b1WghRJHb+6w1KRDfJXPGSbxRFbmLPFGQNJCqs4JhVZoqByBZuk0/MaySypslkC5E8eQQoxxkgQopHmBF4lLzcg7guXK11+bwNnwXmLwcAdfK0PyRePUlqVvqUAc6CnUkYTJ+2FpG0d/gdtVmcMdQd/LeTiOZOnJcRUkpyfszk8zA9/0VX74qR/yoEnCxnE8wkR/7RYJTZOPX7oJfX/UycdxcMlXHm/eXrMQ1vY/Dp0GbmRh4QLBcx40HJkcP8rAw43459WmVsCoqCFIDm8ETDUfrZpcsRjoDmZp3T065gQbbYlaDNbSPJlSx4+WBCIuUl7xaaFth/drm8cj4XphTkroTL3DKCHlJEz2xO3O+vbP2hC5tlcjCgSsq2DP0AWusrCmrSoFvJB2ZIH5pggvbN15OWTt8y2OKQSQ1SZWxLoelHSOs81dp7fY3NFwVOapNVvhbNym8j0xTnrtpaxE+9cJUjeP23XpHNx1UfzHACC6fJF+ru3fHGhwemLFCiMmbEyeSAJOYcBtR3vjSyaoZZqwi0H8GT3MlOjnsv/3At9ogzcmm4crkyeKBCJGAV7YndHUWZVe7IcwJPJwsKKf3JqPxvTw4+s9ZbvCuQRpAhXsr1lvLFtaHHeojKXASh1Znu844OmiQdlzrLI2qnlE2QkT6tB922yJlpfvZPidDxHrvVolAuUOlQ42MueznpXWUhce+Y0mcnTasTIgrn50NDGutmQ36ym3XJIl7rI5Ii3/UwTYp3UFWmbPlOrEA3T1fWzEMxQoCDBFHjCQCctjrhGtj8hOhE1EM/FjQipXyIFhyvGsfpPT+1LJvTIvyIIpoxlycMqx6OG7zSN2d3M3GNn3uRBQBCMyYSu6+IuXJDQig3fHXZ4I8F5q9L5E6SpsXoqxcb1HWcbJx/5PBXBojGnyUAeG6ecvvDmbdORkKmQtNMbUpSRgwHr76jXW1guRo0/KHvzV+24OBL6CX+CQGhy/RB5lUqh5fIGhaciFA3RV063jAxsSLI6zEgs7q2xZclDe9ByYMS7Ibg4b827H0cYIsm++LBh4N+1vlo/JoxLTY95Tv/h6Ou/7EBO41OkPQBSwPOxiFHE7LOYvixWFluc1PNQYCR0MXcMoCWISKsz9qBvY+e5xtkJF1o6g5HDkIp8HGRp8uRB+KoWC1E2XMTmiqKM3/x8O6ZKENLc8IOAXZiznfnTYW9lEAGLZ7D6TW1DDQeHAzM28J2ZP7yANichxbhsYNbWfHiwfNMCE6TBfTF0WNTo9LzFHr/2r4aui7vBoqcyKHvL4h/kWZo8BDKf0k6PuXe2juR9aZLkKUPq+ic7oS3I4CfFQPJmrijc0MKsTV5uUDgz5ga7uw8+9E/ZM/AH7+PwMFpCgK+7fmknLxCjdyu3tYyBe4cnEoQOr6Ulli/uKg/durqt82yjw8fAiBWnK1gSy8qm2Z54eKdqz8Fhq7TQxlzvtYIA74Zw77UXBntqXOXhb5Vx/Ipp40f+FYsSjRg/fPclnieajwwmohSiGAGUiFOJpyRROvVUEfRPOj/+a+vjEZ/DF4FZiDPGa+f3DPVWv/F2h6c85J+xrTp/6QonwC3zKQLh+GhgQ/uZZpsrZjCWkjlNBvIMNOefdPRf3/LyyZtQpJwuitlaHbGZcfe1Cw2YoSyYGV4PVsxW6eDwZ3/bx8Yod2UI/KU40lcVrKjxc6xO5t5sS0w89L3/xyPhRTN8HQRCbkIqagILc9Z//P7oyd9ccVeEAqvKHz4axZW2JPu7t/Rf36o3SMsCB2eyxUt+YDXTcfdUUscm9G+83b6pfgbVJcsVke5mGTiI299/d+xBb7V3w6LkJLMArg/9RP2TD3dwSRLR3fDScFXdHIhMO3Lq8umWUMAs9VL/v3CQX4iw1RE/8esr4HJ+yoGc0GokA4TogYqkkiSX1KEPQ3Jn725EyXAxMcbw5YXdfV11mBoKnlHSDK6YLcGSmDn/VibysJqwmuXVgZO/vYzFysbU4WUWR8xij3Wcbe76aBcMS64+UMrR9Gk0vJGVZJMymllt+tckq8fa0ZbEkiEP/tA7Gk3J7//kqx37RuFj8WI8OT/pgNBhJHYPA68k8FpmpRsjGIO0UWlNyJby4rsHA7NWly8Cc1tanXwaK5CnSd/JC0zbt+8de/Odq+EFk3Q/aBlHh1kROgFVBxnQca7x3q2a9D2RVOEeDFRJKy1Kg8m86BhbZNHMseSBVwd27H80NeqdGnVPjvhmvnHRFlan4zfvmGo73ouBBf1WKUaeGZp0fIHiwTTUe2rUMzXm7r1Wz4Rop7d4+yZZYmXyNOn5hIOmXa0jR0/coowpcCMdg3p6IumTNkg4RDp0Eh4arY+7PETqhOLHKdiF3sYYI3oJlGooPx4gd+E1+BQZDphRFF/7eXd1/QzaFWThk4nIFgmtZ4rTDfZUD9zYMj3ujjMGFG+8veTl7VlkRZ7UNvDE/KTzhYZvDr/eU1nrhwOE/5Rmmy4qWB3E8tyEq/vjnSjpRhMLtSntbDEsUIXo+ZZoI3fBHxLulZ9+1fi9ocCsHaRqJMoFsz1upLnB29U3Pn1xYtiH9yIcSXL9fn0xK/JkaNMHNfUU33zk/ramcXSmoA4zR5c6/9h550btwI3ayKIJdYUs+kZDTkBqMmEjUuoHP7vefHgINhUdN573TzuQcGAOg0f+aaWFWb+z0KTJy/YAkuy74Na6P9rV37118/bput0TmPaju5Vfd22FU7A4Y+jn8LJ1Pue09U8gwi69dwDx13LsHqS+78u68cFyODL4VR2VWv+zkJHzN2MxYRh6yCYqHNIuwRiMFhYeb/3YsGyA/IvHKJIQN9bNjt6vkGqbMwZdWbci+SxyyLwnwPTQcqGNA1sCFMbDaNJ5uQbDW0Mg/xBwsDNDfRvREtBlbHrftdTDyhF5fldBk66CZEnux6wSEHBo5mzOmKYUe8qrgnXngFVkD5U8BUMlT8FQyVMwVPIUDJU8BUMlT8FQyVMwVPIUDJU8BUMlT8FQyVMwVPIUDJU8BUMlT8FQyVMwVPIUDJU8BUMlT8HQrt9TpSpWgpp5CsZ/ASjhDW0NCmVuZHN0cmVhbQplbmRvYmoKOCAwIG9iago8PAovRjEgMTEgMCBSCi9GMiAxMiAwIFIKPj4KZW5kb2JqCjkgMCBvYmoKPDwKL0JpdHNQZXJDb21wb25lbnQgOAovUHJlZGljdG9yIDE1Ci9Db2x1bW5zIDE0OAovQ29sb3JzIDMKPj4KZW5kb2JqCjEwIDAgb2JqCjw8Ci9MZW5ndGggMjAxOQovVHlwZSAvWE9iamVjdAovU3VidHlwZSAvSW1hZ2UKL0ZpbHRlciAvRmxhdGVEZWNvZGUKL0JpdHNQZXJDb21wb25lbnQgOAovV2lkdGggMTQ4Ci9IZWlnaHQgNTkKL0NvbG9yU3BhY2UgL0RldmljZUdyYXkKPj4Kc3RyZWFtDQp4nO2ZeXRORxTAJypBSWyhoSKRRBq1RRbkI0pircbSYytRqnIcqThHUZJyjpYSLYk0qFCEpNVU7bR6gkNDrbHUWpGQCtJDEBFkkem9M2//vpfP9yr0j94/Mnfu3Df3982bN3NnQsh/XKpFLnvZCFqZkkvpHlSaBjbXiLvLSyEKOUtR9oLqkU8r1EJPvgykeVSQq96EtK6gGsl6CUgbpeh3IqDq81jDdEryjNi5BWXbprjeVYv0ixA6J8aHG/ye6jHJ9PR45ypEEuIUT5ZNXfWYlirNPasMaRYPsM9VafQt02e6lZWd8wjNFQ2rCKk9D/ut2hpRrs8UCmWjKHT4ihv7zkuaayKki8nkSDy7m0wegrOXydSriRGmKyzqGrVxZmXvzsS0EaCdRaXNUeazbAz86UaC4O9je+ZRsxR0NwNI41iHh9XGKN3vbqk8jSBiPhStlG8ZcH+FIpI5TAZtgQEkko9dldVX2SbQSplCmOYC32YulLnocO1YKXMMIqQdFNeZx3VKy181gDSQdTVJZRurRdIwtWHaZtB+JmQkto8lpFmcwEQyoBwAZX8oFxpAIjuxp5sq0xAzJA3TgWlvdx+NkfEtItpHrGmmwBQMZSaUh2H86xhAcmRDPl1p6m+OpLc+rQXDOVgbeJO/wERw6wwgbY3OJg7QSGHpZQFJhykJDWI2wftiTANA2UySDc4mMhf7PqowaBZwOm6QGVP58i33KC3YFMoMsJSc4U0TRCbkfBwKH0+8ESS+rSyW6x01SLGEDDIbpxakjkcLcQgOgsGbaSclpjGgwVdZUc8Q0yE2FlLVt1SNtASNnR/SYyqmXsoeFoLhUjNQllOJiRRQzW+1RS7hs++INW9NjvINN3uVUBWTaut1R8cnKSuzqYJpKurljsaY8vDh7kKleaEaKUX0apMmdW/GJG7hkOmUSkz2ueIgG5AcKsd4PV+NlKbwqykqm6BhoLqPRdx9YSjl2zPKatCNJg2Z2Nt7TG15Q420VfRxVn7RYV9+Eeup6aTruqy8A5Gk3sL5C5pzy2v3KV1qEInsxugxTN2uRkqXfPplNbC1WxxNmx8ShX0sPzF1qAopQ/YZQbPr2tYrbsOJRpHIhxi/gOt/KJCO2ck+MDcuO9nUKyZUzoaZPBhBX6Z7y0jn7GWXarBo0+tNbei0Dzyw0jASIRcVc2eEiHS5psIjnJlsSGEd8Ec0su6nK5+yiK15ZRhPGa+qMryraNpgQ5cTaUm5wSWcizOjyBRqLbdC5abqN05hDp1s6NLN1aWZfqu9k5NTdSs9rGYxPxGrvot2qLJ6Tz7lbUCyIoOLioq6WfFpyKeQzknb/i/W6i8Zwg/3lfT2KSkpo2xlGqUfTJYZHOotS201jlPNbPocz0uCDLNxojHBZbCHVa/rHOp98xYfljbQ8tqyCXd8YaMl/UCPqxqmYGEFWNNY0zBROAuPV9iQ6Wn7f8n0DPcM3wtQD2YrrgzsRh4XzEeUviwzKnnDnKn/nCWz+sh+XaOXTAX0wA5+eHRxDfRvS0j36eNrMaaWpGPMkmkdmaNfgG+A+B229/PrIqgOUt5Utjmqi6tjHecO4Um50qKuujhkTLTQS8M0giU99FIYr77JTlp03hjKs7NkTNoToeKBTCUDVrLm3bhkoHUVfyoM1ANioBCqkKf37hYr66NVY8qZ6J2mKqZoyXsIVn2UFyD48ayldG8sVtwYk9hUALOlMSp8kT4Bmq8UaRnVlR+JlqkCk/Z8ZwVTb3RcF7sHC8zkrqGSz7NhGgyGJEp5pu8tph+5Rfj3sBB7LntzVJkhEXJZDynPzpxpJISgOfXZuZ4x3YKBawXlsApKPxOO65E1iNcqBRNsFsN6zHLnTHGepOEcVODFukBRWA2c0kBppwjlrsfUipgxQYILx276J0sqkAmPqQGsNZ799B1UPK7PVzCd5x0gE7+eWEx5+vADlBF8l0tXxRplGWmsBokxRRJyGoqNIaWcCSJXJCenpqaugqNZHss1hBuIHjLTIzeZif9Qh2I+pTFHukbIF1S8HZFkhSWkFVokxgTrVa0zUD4u4UzJqmfYq9zOvd+Vmc4RmYlfquFhgF2q4Y1VJ3JfO0xEOC6oxcLWKzCRGhe4CzLBtClPP3iIScYWtjEc4t4TZKYLCiZhHcsWEpIAfIl42+CnjVa3UIt0t7bWR2YiTlckpo9hAVFe0MJiW8YXtRMy00UFEz8S4T3ADqYdgR8Fy8d+83D+WqZ25j4yE6mXLTLhB5LJs+UP8OiMy+AJPFZ8TS0z0Wh8CleMGczWk8fzJeYSrkYaasFFwUScbwpM+PLojehuwZP2sY3IB5/+e0X8earHRE8lJj/BUthi2V6/z1I8fvMjymyLLgom4pInruNnpKd2YTVerN0qs8T0sEBsjxSMYfh/i0CLAcl3MtJ6yx64Q0hJaZO7NJUpDmnCU7cHs/oaXls8nPJD0S5YLYRnIsDUR9j150rdPqD0d8sBCflNRMrQceiRkJAQJNU8tou/tNf683fy9k8T7zoGbcu9fTSKNAVvPMkPT0iIEVp8ExISHcis0wXZG+QUeFyF7jBBhsKzOJrzip6HvtRWP2Pl3lD5TVd/qD8IIA3Y5cqDF/uPzQX6s4mJ2yOdVaDqBHe6yk9GbZ/hXPF8BTfhLpW7BFo7fj1nMVkdphcudun0SXGQdb//RS3/AHtGoO0NCmVuZHN0cmVhbQplbmRvYmoKMTEgMCBvYmoKPDwKL1R5cGUgL0ZvbnQKL1N1YnR5cGUgL1R5cGUxCi9CYXNlRm9udCAvSGVsdmV0aWNhLUJvbGQKL0VuY29kaW5nIC9XaW5BbnNpRW5jb2RpbmcKPj4KZW5kb2JqCjEyIDAgb2JqCjw8Ci9UeXBlIC9Gb250Ci9TdWJ0eXBlIC9UeXBlMQovQmFzZUZvbnQgL0hlbHZldGljYQovRW5jb2RpbmcgL1dpbkFuc2lFbmNvZGluZwo+PgplbmRvYmoKeHJlZgowIDEzCjAwMDAwMDAwMDAgNjU1MzUgZg0KMDAwMDAwMDAxNSAwMDAwMCBuDQowMDAwMDAwMTk4IDAwMDAwIG4NCjAwMDAwMDAwNzggMDAwMDAgbg0KMDAwMDAwMDI1NSAwMDAwMCBuDQowMDAwMDAwMzcxIDAwMDAwIG4NCjAwMDAwMDEwODggMDAwMDAgbg0KMDAwMDAwMTE0NyAwMDAwMCBuDQowMDAwMDAzOTA2IDAwMDAwIG4NCjAwMDAwMDM5NDkgMDAwMDAgbg0KMDAwMDAwNDAyNyAwMDAwMCBuDQowMDAwMDA2MjE5IDAwMDAwIG4NCjAwMDAwMDYzMjIgMDAwMDAgbg0KdHJhaWxlcgo8PAovUm9vdCAxIDAgUgovSW5mbyAzIDAgUgovSUQgWzxFQkFFOTU0ODEwNUM3QjA4QkUxMTkyQUVDQ0I0OEM1Nz4gPEVCQUU5NTQ4MTA1QzdCMDhCRTExOTJBRUNDQjQ4QzU3Pl0KL1NpemUgMTMKPj4Kc3RhcnR4cmVmCjY0MjAKJSVFT0YK"






        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              examples:
                Unauthorized:
                  description: Unauthorized
                  value:
                    status: UNAUTHORIZED
                    timestamp: 23-05-2022 02:03:26
                    message: UNAUTHORIZED
                    debugMessage: null
                    subErrors: null
        "400":
          description: Please enter valid template details & content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              examples:
                Invalid Template:
                  description: Invalid Template
                  value:
                    status: BAD_REQUEST
                    timestamp: 23-05-2022 01:41:13
                    message: Please Enter Valid Template!
                    debugMessage: null
                    subErrors:
                      - object: template
                        field: name
                        rejectedValue: NotBlank
                        message: Template name is mandatory
                      - object: template
                        field: templateContent
                        rejectedValue: NotNull
                        message: Template content is mandatory
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              examples:
                Internal server error:
                  description: Internal server error
                  value:
                    status: INTERNAL_SERVER_ERROR
                    timestamp: 23-05-2022 01:45:48
                    message: Something Went Wrong
                    debugMessage: null
                    subErrors: null
  /api/v1/templates:
    get:
      tags:
        - Templates
      description: Get template list based on aapId and status.
      operationId: Template-list
      parameters:
        - name: appId
          in: query
          required: true
          schema:
            type: string
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum:
              - ACTIVE
              - INACTIVE
        - name: type
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Templates
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
              examples:
                Get Template List:
                  description: Get Template List
                  value:
                    templates:
                      - appId: "0123"
                        name: Test
                        templateContent:
                          contentType: BASE64
                          data: PCFET0NUWVBFIGh0bWwNCglQVUJMSUMgIi0vL1czQy8vRFREIFhIVE1MIDEuMCBUcmFuc2l0aW9uYWwvL0VOIiAiaHR0cDovL3d3dy53My5vcmcvVFIveGh0bWwxL0RURC94aHRtbDEtdHJhbnNpdGlvbmFsLmR0ZCI+DQo8aHRtbCB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94aHRtbCINCgl4bWxuczp0aD0iaHR0cDovL3d3dy50aHltZWxlYWYub3JnIg0KCXhtbG5zOmxheW91dD0iaHR0cDovL3d3dy51bHRyYXEubmV0Lm56L3RoeW1lbGVhZi9sYXlvdXQiPg0KDQo8aGVhZD4NCjx0aXRsZT5UcmFuc2FjdGlvbiBSZWNlaXB0PC90aXRsZT4NCjxsaW5rIGhyZWY9J2h0dHA6Ly9mb250cy5nb29nbGVhcGlzLmNvbS9jc3M/ZmFtaWx5PVJvYm90bycNCglyZWw9J3N0eWxlc2hlZXQnIHR5cGU9J3RleHQvY3NzJyAvPg0KDQo8c3R5bGU+DQp0YWJsZSB7DQoJcGFkZGluZzogM3B4IDZweCAzcHggNnB4ICFpbXBvcnRhbnQ7DQp9DQoNCmJvZHkgew0KCWZvbnQtZmFtaWx5OiAnQ2FsaWJyaScsIHNhbnMtc2VyaWY7DQp9DQoNCnRyIHsNCglwYWRkaW5nOiA1cHggMHB4IDVweCAwcHggIWltcG9ydGFudDsNCgltYXJnaW46IDVweCAwcHggNXB4IDBweCAhaW1wb3J0YW50Ow0KCS8qb3V0bGluZTogdGhpbiBzb2xpZDsqLw0KfQ0KDQp0ZCB7DQoJcGFkZGluZzogMHB4IDBweCAwcHggMHB4ICFpbXBvcnRhbnQ7DQoJbWFyZ2luOiAwcHggMHB4IDBweCAwcHggIWltcG9ydGFudDsNCgkvKmJvcmRlci1yaWdodDogMXB4IHNvbGlkIGJsYWNrOyovDQp9DQoNCmgyIHsNCglwYWRkaW5nOiA1cHggMHB4IDVweCAwcHggIWltcG9ydGFudDsNCgltYXJnaW46IDVweCAwcHggNXB4IDBweCAhaW1wb3J0YW50Ow0KfQ0KDQpoNCB7DQoJcGFkZGluZzogNXB4IDJweCAycHggNXB4ICFpbXBvcnRhbnQ7DQoJbWFyZ2luOiA1cHggMnB4IDJweCA1cHggIWltcG9ydGFudDsNCgljb2xvcjogIzMzMzMzMyAhaW1wb3J0YW50Ow0KCWZvbnQtc2l6ZTogMThweCAhaW1wb3J0YW50Ow0KfQ0KDQpzdHJvbmcgew0KCXBhZGRpbmc6IDVweCAwcHggMTBweCA1cHggIWltcG9ydGFudDsNCgltYXJnaW46IDVweCAwcHggMnB4IDVweCAhaW1wb3J0YW50Ow0KCWNvbG9yOiAjMzMzMzMzICFpbXBvcnRhbnQ7DQoJZm9udC1zaXplOiAxNnB4ICFpbXBvcnRhbnQ7DQp9DQoNCnAgew0KCXBhZGRpbmc6IDJweCA2cHggMnB4IDZweCAhaW1wb3J0YW50Ow0KCW1hcmdpbjogMnB4IDZweCAycHggNnB4ICFpbXBvcnRhbnQ7DQp9DQoNCmhyIHsNCglib3JkZXI6IDAuNXB4IHNvbGlkICM4RTkwOTA7DQoJbWFyZ2luOiA1cHggMHB4IDVweCAwcHggIWltcG9ydGFudDsNCn0NCg0KLnVzZXItaW1hZ2Ugew0KCXdpZHRoOiAxMDBweCAhaW1wb3J0YW50Ow0KCWhlaWdodDogMTAwcHggIWltcG9ydGFudDsNCglib3JkZXI6IDJweCBzb2xpZCAjQkZDMkM0ICFpbXBvcnRhbnQ7DQoJYm9yZGVyLWNvbGxhcHNlOiBzZXBhcmF0ZSAhaW1wb3J0YW50Ow0KCXBlcnNwZWN0aXZlOiAxcHggIWltcG9ydGFudDsNCglvdmVyZmxvdzogaGlkZGVuICFpbXBvcnRhbnQ7DQp9DQo8L3N0eWxlPg0KPC9oZWFkPg0KDQo8Ym9keSBzdHlsZT0id2lkdGg6IDUwJTsiPg0KCTxkaXY+DQoNCgkJPHRhYmxlIHdpZHRoPSIxMDAlIj4NCgkJCTx0Ym9keT4NCgkJCQk8dHI+DQoJCQkJCTx0ZCB3aWR0aD0iMjAlIj48aW1nIHNyYz0iaHR0cHM6Ly9wYXluZWFyYnkuaW4vd3AtY29udGVudC90aGVtZXMvcGF5bmVhcmJ5L2Fzc2V0cy9pbWFnZXMvbG9nby5wbmciIHdpZHRoPSI5MCINCgkJCQkJCWhlaWdodD0iMzUiIHN0eWxlPSJtYXJnaW4tbGVmdDogMjBweDsiIGFsdD0iIj48L3RkPg0KCQkJCQk8dGQgd2lkdGg9IjgwJSI+PGgyPlRyYW5zYWN0aW9uIFJlY2VpcHQ8L2gyPjwvdGQ+DQoJCQkJPC90cj4NCgkJCTwvdGJvZHk+DQoJCTwvdGFibGU+DQoJCTxici8+DQoJPC9kaXY+DQoJDQoJIDxkaXY+DQoNCgkJCQk8dGFibGUgd2lkdGg9IjEwMCUiPg0KCQkJCQk8dGJvZHk+DQoJCQkJCQk8dHI+DQoJCQkJCQkJPHRkIGNvbHNwYW49IjIiPg0KCQkJCQkJCQk8aDQ+Q3VzdG9tZXIgRGV0YWlsczo8L2g0Pg0KCQkJCQkJCTwvdGQ+DQoNCgkJCQkJCTwvdHI+DQoJCQkJCQk8dHI+DQoJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQk8cD5Nb2JpbGUgTnVtYmVyIChTTVMpPC9wPg0KCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQk8cCB0aDp1dGV4dD0iJHtjdXN0b21lck1vYmlsZX0iPjwvcD4NCgkJCQkJCQk8L3RkPg0KCQkJCQkJPC90cj4NCgkJCQkJCTx0cj4NCgkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCTxwPkN1c3RvbWVyIE5hbWU8L3A+DQoJCQkJCQkJPC90ZD4NCgkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCTxwIHRoOnV0ZXh0PSIke2N1c3RvbWVyTmFtZX0iPjwvcD4NCgkJCQkJCQk8L3RkPg0KCQkJCQkJPC90cj4NCgkJCQkJPC90Ym9keT4NCgkJCQk8L3RhYmxlPg0KCQkJCTxici8+DQoJCQk8L2Rpdj4gPGJyLz4NCgkJCQk8ZGl2Pg0KCQkJCQk8dGFibGUgd2lkdGg9IjEwMCUiPg0KCQkJCQkJPHRib2R5Pg0KCQkJCQkJCTx0cj4NCgkJCQkJCQkJPHRkIGNvbHNwYW49IjIiPg0KCQkJCQkJCQkJPGg0PlRyYW5zYWN0aW9uIERldGFpbHM6PC9oND4NCgkJCQkJCQkJPC90ZD4NCgkJCQkJCQk8L3RyPg0KCQkJCQkJCTx0cj4NCgkJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQkJPHA+VHJhbnNhY3Rpb24gU3RhdHVzPC9wPg0KCQkJCQkJCQk8L3RkPg0KCQkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCQk8cCB0aDp1dGV4dD0iJHt0cmFuc2FjdGlvblN0YXR1c30iPjwvcD4NCgkJCQkJCQkJPC90ZD4NCgkJCQkJCQk8L3RyPg0KCQkJCQkJCTx0cj4NCgkJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQkJPHA+VHJhbnNhY3Rpb24gSUQ8L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwIHRoOnV0ZXh0PSIke3RyYW5zYWN0aW9uSUR9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCgkJCQkJCQk8dHI+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwPlRyYW5zYWN0aW9uIERhdGUgJiBUaW1lPC9wPg0KCQkJCQkJCQk8L3RkPg0KCQkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCQk8cCB0aDp1dGV4dD0iJHt0aW1lU3RhbXB9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCgkJCQkJCQk8dHI+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwPlBheW1lbnQgTWV0aG9kPC9wPg0KCQkJCQkJCQk8L3RkPg0KCQkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCQk8cCB0aDp1dGV4dD0iJHtwYXltZW50TWV0aG9kfSI+PC9wPg0KCQkJCQkJCQk8L3RkPg0KCQkJCQkJCTwvdHI+DQoJCQkJCQkJPHRyPg0KCQkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCQk8cD5UcmFuc2FjdGlvbiBNb2RlPC9wPg0KCQkJCQkJCQk8L3RkPg0KCQkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCQk8cCB0aDp1dGV4dD0iJHt0cmFuc2FjdGlvbk1vZGV9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCgkJCQkJCQk8dHI+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwPlRyYW5zYWN0aW9uIEFtb3VudDwvcD4NCgkJCQkJCQkJPC90ZD4NCgkJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7dHJhbnNhY3Rpb25BbW91bnR9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCgkJCQkJCQk8dHI+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwPkNvbnZlbmllbmNlIEZlZTwvcD4NCgkJCQkJCQkJPC90ZD4NCgkJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7Y29udmVuaWVuY2VGZWV9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCgkJCQkJCQk8dHI+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwPlRvdGFsIEFtb3VudDwvcD4NCgkJCQkJCQkJPC90ZD4NCgkJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7dG90YWxBbW91bnR9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCg0KCQkJCQkJPC90Ym9keT4NCgkJCQkJPC90YWJsZT4NCgkJCQk8L2Rpdj48YnIvPg0KCQkJCTxkaXY+DQoNCgkJCQk8dGFibGUgd2lkdGg9IjEwMCUiPg0KCQkJCQk8dGJvZHk+DQoJCQkJCQk8dHI+DQoJCQkJCQkJPHRkIGNvbHNwYW49IjIiPg0KCQkJCQkJCQk8aDQ+QmVuaWZpY2lhcnkgRGV0YWlsczo8L2g0Pg0KCQkJCQkJCTwvdGQ+DQoNCgkJCQkJCTwvdHI+DQoJCQkJCQk8dHI+DQoJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQk8cD5CZW5pZmljaWFyeSBOYW1lIDwvcD4NCgkJCQkJCQk8L3RkPg0KCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7YmVuaWZpY2lhcnlOYW1lfSI+PC9wPg0KCQkJCQkJCTwvdGQ+DQoJCQkJCQk8L3RyPg0KCQkJCQkJPHRyPg0KCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJPHA+QmVuaWZpY2lhcnkgQmFuazwvcD4NCgkJCQkJCQk8L3RkPg0KCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7YmVuaWZpY2lhcnlCYW5rfSI+PC9wPg0KCQkJCQkJCTwvdGQ+DQoJCQkJCQk8L3RyPg0KCQkJCQkJDQoJCQkJCQk8dHI+DQoJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQk8cD5CZW5pZmljaWFyeSBBY2NvdW50IE51bWJlcjwvcD4NCgkJCQkJCQk8L3RkPg0KCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7YmVuaWZpY2lhcnlBY2NvdW50TnVtYmVyfSI+PC9wPg0KCQkJCQkJCTwvdGQ+DQoJCQkJCQk8L3RyPg0KCQkJCQkJPHRyPg0KCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJPHA+QmFuayBJRlNDIENvZGU8L3A+DQoJCQkJCQkJPC90ZD4NCgkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCTxwIHRoOnV0ZXh0PSIke2JhbmtJRlNDQ29kZX0iPjwvcD4NCgkJCQkJCQk8L3RkPg0KDQoJCQkJCQk8L3RyPg0KCQkJCQk8L3Rib2R5Pg0KCQkJCTwvdGFibGU+DQoJCQkJPGJyLz4NCgkJCTwvZGl2PiANCjwvYm9keT4NCg0KPC9odG1sPg==
                        status: ACTIVE
                        type: MINI STATEMENT
                        id: 628b42b31c9bc37e1cd3338b
                        tag: INVOICE
                        createdDate: 2022-05-23 13:45:47
                        lastModifiedDate: 2022-05-23 13:45:47
        "400":
          description: Please enter valid appId & status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              examples:
                Invalid request:
                  description: Invalid request
                  value:
                    status: BAD_REQUEST
                    timestamp: 23-05-2022 02:43:17
                    message: AppId id must not be null!
                    debugMessage: null
                    subErrors: null
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              examples:
                Unauthorized:
                  description: Unauthorized
                  value:
                    status: UNAUTHORIZED
                    timestamp: 23-05-2022 02:03:26
                    message: UNAUTHORIZED
                    debugMessage: null
                    subErrors: null
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              examples:
                Internal server error:
                  description: Internal server error
                  value:
                    status: INTERNAL_SERVER_ERROR
                    timestamp: 23-05-2022 01:45:48
                    message: Something Went Wrong
                    debugMessage: null
                    subErrors: null
    post:
      tags:
        - Templates
      description: Creates a new template. If template configuration is not specified
        in the request body then an empty template is created. Template configuration
        must be sent in the request body.
      operationId: register-template_1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Template'
        required: true
      responses:
        "201":
          description: Template created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
              examples:
                Template created:
                  description: Template created
                  value:
                    appId: "12345543210"
                    name: 'Test Template '
                    templateContent:
                      contentType: BASE64
                      data: PCFET0NUWVBFIGh0bWwNCglQVUJMSUMgIi0vL1czQy8vRFREIFhIVE1MIDEuMCBUcmFuc2l0aW9uYWwvL0VOIiAiaHR0cDovL3d3dy53My5vcmcvVFIveGh0bWwxL0RURC94aHRtbDEtdHJhbnNpdGlvbmFsLmR0ZCI+DQo8aHRtbCB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94aHRtbCINCgl4bWxuczp0aD0iaHR0cDovL3d3dy50aHltZWxlYWYub3JnIg0KCXhtbG5zOmxheW91dD0iaHR0cDovL3d3dy51bHRyYXEubmV0Lm56L3RoeW1lbGVhZi9sYXlvdXQiPg0KDQo8aGVhZD4NCjx0aXRsZT5UcmFuc2FjdGlvbiBSZWNlaXB0PC90aXRsZT4NCjxsaW5rIGhyZWY9J2h0dHA6Ly9mb250cy5nb29nbGVhcGlzLmNvbS9jc3M/ZmFtaWx5PVJvYm90bycNCglyZWw9J3N0eWxlc2hlZXQnIHR5cGU9J3RleHQvY3NzJyAvPg0KDQo8c3R5bGU+DQp0YWJsZSB7DQoJcGFkZGluZzogM3B4IDZweCAzcHggNnB4ICFpbXBvcnRhbnQ7DQp9DQoNCmJvZHkgew0KCWZvbnQtZmFtaWx5OiAnQ2FsaWJyaScsIHNhbnMtc2VyaWY7DQp9DQoNCnRyIHsNCglwYWRkaW5nOiA1cHggMHB4IDVweCAwcHggIWltcG9ydGFudDsNCgltYXJnaW46IDVweCAwcHggNXB4IDBweCAhaW1wb3J0YW50Ow0KCS8qb3V0bGluZTogdGhpbiBzb2xpZDsqLw0KfQ0KDQp0ZCB7DQoJcGFkZGluZzogMHB4IDBweCAwcHggMHB4ICFpbXBvcnRhbnQ7DQoJbWFyZ2luOiAwcHggMHB4IDBweCAwcHggIWltcG9ydGFudDsNCgkvKmJvcmRlci1yaWdodDogMXB4IHNvbGlkIGJsYWNrOyovDQp9DQoNCmgyIHsNCglwYWRkaW5nOiA1cHggMHB4IDVweCAwcHggIWltcG9ydGFudDsNCgltYXJnaW46IDVweCAwcHggNXB4IDBweCAhaW1wb3J0YW50Ow0KfQ0KDQpoNCB7DQoJcGFkZGluZzogNXB4IDJweCAycHggNXB4ICFpbXBvcnRhbnQ7DQoJbWFyZ2luOiA1cHggMnB4IDJweCA1cHggIWltcG9ydGFudDsNCgljb2xvcjogIzMzMzMzMyAhaW1wb3J0YW50Ow0KCWZvbnQtc2l6ZTogMThweCAhaW1wb3J0YW50Ow0KfQ0KDQpzdHJvbmcgew0KCXBhZGRpbmc6IDVweCAwcHggMTBweCA1cHggIWltcG9ydGFudDsNCgltYXJnaW46IDVweCAwcHggMnB4IDVweCAhaW1wb3J0YW50Ow0KCWNvbG9yOiAjMzMzMzMzICFpbXBvcnRhbnQ7DQoJZm9udC1zaXplOiAxNnB4ICFpbXBvcnRhbnQ7DQp9DQoNCnAgew0KCXBhZGRpbmc6IDJweCA2cHggMnB4IDZweCAhaW1wb3J0YW50Ow0KCW1hcmdpbjogMnB4IDZweCAycHggNnB4ICFpbXBvcnRhbnQ7DQp9DQoNCmhyIHsNCglib3JkZXI6IDAuNXB4IHNvbGlkICM4RTkwOTA7DQoJbWFyZ2luOiA1cHggMHB4IDVweCAwcHggIWltcG9ydGFudDsNCn0NCg0KLnVzZXItaW1hZ2Ugew0KCXdpZHRoOiAxMDBweCAhaW1wb3J0YW50Ow0KCWhlaWdodDogMTAwcHggIWltcG9ydGFudDsNCglib3JkZXI6IDJweCBzb2xpZCAjQkZDMkM0ICFpbXBvcnRhbnQ7DQoJYm9yZGVyLWNvbGxhcHNlOiBzZXBhcmF0ZSAhaW1wb3J0YW50Ow0KCXBlcnNwZWN0aXZlOiAxcHggIWltcG9ydGFudDsNCglvdmVyZmxvdzogaGlkZGVuICFpbXBvcnRhbnQ7DQp9DQo8L3N0eWxlPg0KPC9oZWFkPg0KDQo8Ym9keSBzdHlsZT0id2lkdGg6IDUwJTsiPg0KCTxkaXY+DQoNCgkJPHRhYmxlIHdpZHRoPSIxMDAlIj4NCgkJCTx0Ym9keT4NCgkJCQk8dHI+DQoJCQkJCTx0ZCB3aWR0aD0iMjAlIj48aW1nIHNyYz0iaHR0cHM6Ly9wYXluZWFyYnkuaW4vd3AtY29udGVudC90aGVtZXMvcGF5bmVhcmJ5L2Fzc2V0cy9pbWFnZXMvbG9nby5wbmciIHdpZHRoPSI5MCINCgkJCQkJCWhlaWdodD0iMzUiIHN0eWxlPSJtYXJnaW4tbGVmdDogMjBweDsiIGFsdD0iIj48L3RkPg0KCQkJCQk8dGQgd2lkdGg9IjgwJSI+PGgyPlRyYW5zYWN0aW9uIFJlY2VpcHQ8L2gyPjwvdGQ+DQoJCQkJPC90cj4NCgkJCTwvdGJvZHk+DQoJCTwvdGFibGU+DQoJCTxici8+DQoJPC9kaXY+DQoJDQoJIDxkaXY+DQoNCgkJCQk8dGFibGUgd2lkdGg9IjEwMCUiPg0KCQkJCQk8dGJvZHk+DQoJCQkJCQk8dHI+DQoJCQkJCQkJPHRkIGNvbHNwYW49IjIiPg0KCQkJCQkJCQk8aDQ+Q3VzdG9tZXIgRGV0YWlsczo8L2g0Pg0KCQkJCQkJCTwvdGQ+DQoNCgkJCQkJCTwvdHI+DQoJCQkJCQk8dHI+DQoJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQk8cD5Nb2JpbGUgTnVtYmVyIChTTVMpPC9wPg0KCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQk8cCB0aDp1dGV4dD0iJHtjdXN0b21lck1vYmlsZX0iPjwvcD4NCgkJCQkJCQk8L3RkPg0KCQkJCQkJPC90cj4NCgkJCQkJCTx0cj4NCgkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCTxwPkN1c3RvbWVyIE5hbWU8L3A+DQoJCQkJCQkJPC90ZD4NCgkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCTxwIHRoOnV0ZXh0PSIke2N1c3RvbWVyTmFtZX0iPjwvcD4NCgkJCQkJCQk8L3RkPg0KCQkJCQkJPC90cj4NCgkJCQkJPC90Ym9keT4NCgkJCQk8L3RhYmxlPg0KCQkJCTxici8+DQoJCQk8L2Rpdj4gPGJyLz4NCgkJCQk8ZGl2Pg0KCQkJCQk8dGFibGUgd2lkdGg9IjEwMCUiPg0KCQkJCQkJPHRib2R5Pg0KCQkJCQkJCTx0cj4NCgkJCQkJCQkJPHRkIGNvbHNwYW49IjIiPg0KCQkJCQkJCQkJPGg0PlRyYW5zYWN0aW9uIERldGFpbHM6PC9oND4NCgkJCQkJCQkJPC90ZD4NCgkJCQkJCQk8L3RyPg0KCQkJCQkJCTx0cj4NCgkJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQkJPHA+VHJhbnNhY3Rpb24gU3RhdHVzPC9wPg0KCQkJCQkJCQk8L3RkPg0KCQkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCQk8cCB0aDp1dGV4dD0iJHt0cmFuc2FjdGlvblN0YXR1c30iPjwvcD4NCgkJCQkJCQkJPC90ZD4NCgkJCQkJCQk8L3RyPg0KCQkJCQkJCTx0cj4NCgkJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQkJPHA+VHJhbnNhY3Rpb24gSUQ8L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwIHRoOnV0ZXh0PSIke3RyYW5zYWN0aW9uSUR9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCgkJCQkJCQk8dHI+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwPlRyYW5zYWN0aW9uIERhdGUgJiBUaW1lPC9wPg0KCQkJCQkJCQk8L3RkPg0KCQkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCQk8cCB0aDp1dGV4dD0iJHt0aW1lU3RhbXB9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCgkJCQkJCQk8dHI+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwPlBheW1lbnQgTWV0aG9kPC9wPg0KCQkJCQkJCQk8L3RkPg0KCQkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCQk8cCB0aDp1dGV4dD0iJHtwYXltZW50TWV0aG9kfSI+PC9wPg0KCQkJCQkJCQk8L3RkPg0KCQkJCQkJCTwvdHI+DQoJCQkJCQkJPHRyPg0KCQkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCQk8cD5UcmFuc2FjdGlvbiBNb2RlPC9wPg0KCQkJCQkJCQk8L3RkPg0KCQkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCQk8cCB0aDp1dGV4dD0iJHt0cmFuc2FjdGlvbk1vZGV9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCgkJCQkJCQk8dHI+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwPlRyYW5zYWN0aW9uIEFtb3VudDwvcD4NCgkJCQkJCQkJPC90ZD4NCgkJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7dHJhbnNhY3Rpb25BbW91bnR9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCgkJCQkJCQk8dHI+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwPkNvbnZlbmllbmNlIEZlZTwvcD4NCgkJCQkJCQkJPC90ZD4NCgkJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7Y29udmVuaWVuY2VGZWV9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCgkJCQkJCQk8dHI+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwPlRvdGFsIEFtb3VudDwvcD4NCgkJCQkJCQkJPC90ZD4NCgkJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7dG90YWxBbW91bnR9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCg0KCQkJCQkJPC90Ym9keT4NCgkJCQkJPC90YWJsZT4NCgkJCQk8L2Rpdj48YnIvPg0KCQkJCTxkaXY+DQoNCgkJCQk8dGFibGUgd2lkdGg9IjEwMCUiPg0KCQkJCQk8dGJvZHk+DQoJCQkJCQk8dHI+DQoJCQkJCQkJPHRkIGNvbHNwYW49IjIiPg0KCQkJCQkJCQk8aDQ+QmVuaWZpY2lhcnkgRGV0YWlsczo8L2g0Pg0KCQkJCQkJCTwvdGQ+DQoNCgkJCQkJCTwvdHI+DQoJCQkJCQk8dHI+DQoJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQk8cD5CZW5pZmljaWFyeSBOYW1lIDwvcD4NCgkJCQkJCQk8L3RkPg0KCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7YmVuaWZpY2lhcnlOYW1lfSI+PC9wPg0KCQkJCQkJCTwvdGQ+DQoJCQkJCQk8L3RyPg0KCQkJCQkJPHRyPg0KCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJPHA+QmVuaWZpY2lhcnkgQmFuazwvcD4NCgkJCQkJCQk8L3RkPg0KCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7YmVuaWZpY2lhcnlCYW5rfSI+PC9wPg0KCQkJCQkJCTwvdGQ+DQoJCQkJCQk8L3RyPg0KCQkJCQkJDQoJCQkJCQk8dHI+DQoJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQk8cD5CZW5pZmljaWFyeSBBY2NvdW50IE51bWJlcjwvcD4NCgkJCQkJCQk8L3RkPg0KCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7YmVuaWZpY2lhcnlBY2NvdW50TnVtYmVyfSI+PC9wPg0KCQkJCQkJCTwvdGQ+DQoJCQkJCQk8L3RyPg0KCQkJCQkJPHRyPg0KCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJPHA+QmFuayBJRlNDIENvZGU8L3A+DQoJCQkJCQkJPC90ZD4NCgkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCTxwIHRoOnV0ZXh0PSIke2JhbmtJRlNDQ29kZX0iPjwvcD4NCgkJCQkJCQk8L3RkPg0KDQoJCQkJCQk8L3RyPg0KCQkJCQk8L3Rib2R5Pg0KCQkJCTwvdGFibGU+DQoJCQkJPGJyLz4NCgkJCTwvZGl2PiANCjwvYm9keT4NCg0KPC9odG1sPg==
                    status: ACTIVE
                    type: MINI STATEMENT
                    id: 6284e6d11f41a5763409d809
                    tag: INVOICE
                    createdDate: 2022-05-18 18:00:09
                    lastModifiedDate: 2022-05-18 18:00:09
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              examples:
                Unauthorized:
                  description: Unauthorized
                  value:
                    status: UNAUTHORIZED
                    timestamp: 23-05-2022 02:03:26
                    message: UNAUTHORIZED
                    debugMessage: null
                    subErrors: null
        "400":
          description: Please enter valid template details & content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              examples:
                Invalid Template:
                  description: Invalid Template
                  value:
                    status: BAD_REQUEST
                    timestamp: 23-05-2022 01:41:13
                    message: Please Enter Valid Template!
                    debugMessage: null
                    subErrors:
                      - object: template
                        field: name
                        rejectedValue: NotBlank
                        message: Template name is mandatory
                      - object: template
                        field: templateContent
                        rejectedValue: NotNull
                        message: Template content is mandatory
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              examples:
                Internal server error:
                  description: Internal server error
                  value:
                    status: INTERNAL_SERVER_ERROR
                    timestamp: 23-05-2022 01:45:48
                    message: Something Went Wrong
                    debugMessage: null
                    subErrors: null
    patch:
      tags:
        - Templates
      description: Unregister or Update an existing template.
      operationId: update-template
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Template'
        required: true
      responses:
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              examples:
                Unauthorized:
                  description: Unauthorized
                  value:
                    status: UNAUTHORIZED
                    timestamp: 23-05-2022 02:03:26
                    message: UNAUTHORIZED
                    debugMessage: null
                    subErrors: null
        "200":
          description: Update Template
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
              examples:
                Update Template:
                  description: Update Template
                  value:
                    appId: "0123"
                    name: Tests1
                    templateContent:
                      contentType: BASE64
                      data: PCFET0NUWVBFIGh0bWwNCglQVUJMSUMgIi0vL1czQy8vRFREIFhIVE1MIDEuMCBUcmFuc2l0aW9uYWwvL0VOIiAiaHR0cDovL3d3dy53My5vcmcvVFIveGh0bWwxL0RURC94aHRtbDEtdHJhbnNpdGlvbmFsLmR0ZCI+DQo8aHRtbCB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94aHRtbCINCgl4bWxuczp0aD0iaHR0cDovL3d3dy50aHltZWxlYWYub3JnIg0KCXhtbG5zOmxheW91dD0iaHR0cDovL3d3dy51bHRyYXEubmV0Lm56L3RoeW1lbGVhZi9sYXlvdXQiPg0KDQo8aGVhZD4NCjx0aXRsZT5UcmFuc2FjdGlvbiBSZWNlaXB0PC90aXRsZT4NCjxsaW5rIGhyZWY9J2h0dHA6Ly9mb250cy5nb29nbGVhcGlzLmNvbS9jc3M/ZmFtaWx5PVJvYm90bycNCglyZWw9J3N0eWxlc2hlZXQnIHR5cGU9J3RleHQvY3NzJyAvPg0KDQo8c3R5bGU+DQp0YWJsZSB7DQoJcGFkZGluZzogM3B4IDZweCAzcHggNnB4ICFpbXBvcnRhbnQ7DQp9DQoNCmJvZHkgew0KCWZvbnQtZmFtaWx5OiAnQ2FsaWJyaScsIHNhbnMtc2VyaWY7DQp9DQoNCnRyIHsNCglwYWRkaW5nOiA1cHggMHB4IDVweCAwcHggIWltcG9ydGFudDsNCgltYXJnaW46IDVweCAwcHggNXB4IDBweCAhaW1wb3J0YW50Ow0KCS8qb3V0bGluZTogdGhpbiBzb2xpZDsqLw0KfQ0KDQp0ZCB7DQoJcGFkZGluZzogMHB4IDBweCAwcHggMHB4ICFpbXBvcnRhbnQ7DQoJbWFyZ2luOiAwcHggMHB4IDBweCAwcHggIWltcG9ydGFudDsNCgkvKmJvcmRlci1yaWdodDogMXB4IHNvbGlkIGJsYWNrOyovDQp9DQoNCmgyIHsNCglwYWRkaW5nOiA1cHggMHB4IDVweCAwcHggIWltcG9ydGFudDsNCgltYXJnaW46IDVweCAwcHggNXB4IDBweCAhaW1wb3J0YW50Ow0KfQ0KDQpoNCB7DQoJcGFkZGluZzogNXB4IDJweCAycHggNXB4ICFpbXBvcnRhbnQ7DQoJbWFyZ2luOiA1cHggMnB4IDJweCA1cHggIWltcG9ydGFudDsNCgljb2xvcjogIzMzMzMzMyAhaW1wb3J0YW50Ow0KCWZvbnQtc2l6ZTogMThweCAhaW1wb3J0YW50Ow0KfQ0KDQpzdHJvbmcgew0KCXBhZGRpbmc6IDVweCAwcHggMTBweCA1cHggIWltcG9ydGFudDsNCgltYXJnaW46IDVweCAwcHggMnB4IDVweCAhaW1wb3J0YW50Ow0KCWNvbG9yOiAjMzMzMzMzICFpbXBvcnRhbnQ7DQoJZm9udC1zaXplOiAxNnB4ICFpbXBvcnRhbnQ7DQp9DQoNCnAgew0KCXBhZGRpbmc6IDJweCA2cHggMnB4IDZweCAhaW1wb3J0YW50Ow0KCW1hcmdpbjogMnB4IDZweCAycHggNnB4ICFpbXBvcnRhbnQ7DQp9DQoNCmhyIHsNCglib3JkZXI6IDAuNXB4IHNvbGlkICM4RTkwOTA7DQoJbWFyZ2luOiA1cHggMHB4IDVweCAwcHggIWltcG9ydGFudDsNCn0NCg0KLnVzZXItaW1hZ2Ugew0KCXdpZHRoOiAxMDBweCAhaW1wb3J0YW50Ow0KCWhlaWdodDogMTAwcHggIWltcG9ydGFudDsNCglib3JkZXI6IDJweCBzb2xpZCAjQkZDMkM0ICFpbXBvcnRhbnQ7DQoJYm9yZGVyLWNvbGxhcHNlOiBzZXBhcmF0ZSAhaW1wb3J0YW50Ow0KCXBlcnNwZWN0aXZlOiAxcHggIWltcG9ydGFudDsNCglvdmVyZmxvdzogaGlkZGVuICFpbXBvcnRhbnQ7DQp9DQo8L3N0eWxlPg0KPC9oZWFkPg0KDQo8Ym9keSBzdHlsZT0id2lkdGg6IDUwJTsiPg0KCTxkaXY+DQoNCgkJPHRhYmxlIHdpZHRoPSIxMDAlIj4NCgkJCTx0Ym9keT4NCgkJCQk8dHI+DQoJCQkJCTx0ZCB3aWR0aD0iMjAlIj48aW1nIHNyYz0iaHR0cHM6Ly9wYXluZWFyYnkuaW4vd3AtY29udGVudC90aGVtZXMvcGF5bmVhcmJ5L2Fzc2V0cy9pbWFnZXMvbG9nby5wbmciIHdpZHRoPSI5MCINCgkJCQkJCWhlaWdodD0iMzUiIHN0eWxlPSJtYXJnaW4tbGVmdDogMjBweDsiIGFsdD0iIj48L3RkPg0KCQkJCQk8dGQgd2lkdGg9IjgwJSI+PGgyPlRyYW5zYWN0aW9uIFJlY2VpcHQ8L2gyPjwvdGQ+DQoJCQkJPC90cj4NCgkJCTwvdGJvZHk+DQoJCTwvdGFibGU+DQoJCTxici8+DQoJPC9kaXY+DQoJDQoJIDxkaXY+DQoNCgkJCQk8dGFibGUgd2lkdGg9IjEwMCUiPg0KCQkJCQk8dGJvZHk+DQoJCQkJCQk8dHI+DQoJCQkJCQkJPHRkIGNvbHNwYW49IjIiPg0KCQkJCQkJCQk8aDQ+Q3VzdG9tZXIgRGV0YWlsczo8L2g0Pg0KCQkJCQkJCTwvdGQ+DQoNCgkJCQkJCTwvdHI+DQoJCQkJCQk8dHI+DQoJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQk8cD5Nb2JpbGUgTnVtYmVyIChTTVMpPC9wPg0KCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQk8cCB0aDp1dGV4dD0iJHtjdXN0b21lck1vYmlsZX0iPjwvcD4NCgkJCQkJCQk8L3RkPg0KCQkJCQkJPC90cj4NCgkJCQkJCTx0cj4NCgkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCTxwPkN1c3RvbWVyIE5hbWU8L3A+DQoJCQkJCQkJPC90ZD4NCgkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCTxwIHRoOnV0ZXh0PSIke2N1c3RvbWVyTmFtZX0iPjwvcD4NCgkJCQkJCQk8L3RkPg0KCQkJCQkJPC90cj4NCgkJCQkJPC90Ym9keT4NCgkJCQk8L3RhYmxlPg0KCQkJCTxici8+DQoJCQk8L2Rpdj4gPGJyLz4NCgkJCQk8ZGl2Pg0KCQkJCQk8dGFibGUgd2lkdGg9IjEwMCUiPg0KCQkJCQkJPHRib2R5Pg0KCQkJCQkJCTx0cj4NCgkJCQkJCQkJPHRkIGNvbHNwYW49IjIiPg0KCQkJCQkJCQkJPGg0PlRyYW5zYWN0aW9uIERldGFpbHM6PC9oND4NCgkJCQkJCQkJPC90ZD4NCgkJCQkJCQk8L3RyPg0KCQkJCQkJCTx0cj4NCgkJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQkJPHA+VHJhbnNhY3Rpb24gU3RhdHVzPC9wPg0KCQkJCQkJCQk8L3RkPg0KCQkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCQk8cCB0aDp1dGV4dD0iJHt0cmFuc2FjdGlvblN0YXR1c30iPjwvcD4NCgkJCQkJCQkJPC90ZD4NCgkJCQkJCQk8L3RyPg0KCQkJCQkJCTx0cj4NCgkJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQkJPHA+VHJhbnNhY3Rpb24gSUQ8L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwIHRoOnV0ZXh0PSIke3RyYW5zYWN0aW9uSUR9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCgkJCQkJCQk8dHI+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwPlRyYW5zYWN0aW9uIERhdGUgJiBUaW1lPC9wPg0KCQkJCQkJCQk8L3RkPg0KCQkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCQk8cCB0aDp1dGV4dD0iJHt0aW1lU3RhbXB9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCgkJCQkJCQk8dHI+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwPlBheW1lbnQgTWV0aG9kPC9wPg0KCQkJCQkJCQk8L3RkPg0KCQkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCQk8cCB0aDp1dGV4dD0iJHtwYXltZW50TWV0aG9kfSI+PC9wPg0KCQkJCQkJCQk8L3RkPg0KCQkJCQkJCTwvdHI+DQoJCQkJCQkJPHRyPg0KCQkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCQk8cD5UcmFuc2FjdGlvbiBNb2RlPC9wPg0KCQkJCQkJCQk8L3RkPg0KCQkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCQk8cCB0aDp1dGV4dD0iJHt0cmFuc2FjdGlvbk1vZGV9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCgkJCQkJCQk8dHI+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwPlRyYW5zYWN0aW9uIEFtb3VudDwvcD4NCgkJCQkJCQkJPC90ZD4NCgkJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7dHJhbnNhY3Rpb25BbW91bnR9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCgkJCQkJCQk8dHI+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwPkNvbnZlbmllbmNlIEZlZTwvcD4NCgkJCQkJCQkJPC90ZD4NCgkJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7Y29udmVuaWVuY2VGZWV9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCgkJCQkJCQk8dHI+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwPlRvdGFsIEFtb3VudDwvcD4NCgkJCQkJCQkJPC90ZD4NCgkJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7dG90YWxBbW91bnR9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCg0KCQkJCQkJPC90Ym9keT4NCgkJCQkJPC90YWJsZT4NCgkJCQk8L2Rpdj48YnIvPg0KCQkJCTxkaXY+DQoNCgkJCQk8dGFibGUgd2lkdGg9IjEwMCUiPg0KCQkJCQk8dGJvZHk+DQoJCQkJCQk8dHI+DQoJCQkJCQkJPHRkIGNvbHNwYW49IjIiPg0KCQkJCQkJCQk8aDQ+QmVuaWZpY2lhcnkgRGV0YWlsczo8L2g0Pg0KCQkJCQkJCTwvdGQ+DQoNCgkJCQkJCTwvdHI+DQoJCQkJCQk8dHI+DQoJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQk8cD5CZW5pZmljaWFyeSBOYW1lIDwvcD4NCgkJCQkJCQk8L3RkPg0KCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7YmVuaWZpY2lhcnlOYW1lfSI+PC9wPg0KCQkJCQkJCTwvdGQ+DQoJCQkJCQk8L3RyPg0KCQkJCQkJPHRyPg0KCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJPHA+QmVuaWZpY2lhcnkgQmFuazwvcD4NCgkJCQkJCQk8L3RkPg0KCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7YmVuaWZpY2lhcnlCYW5rfSI+PC9wPg0KCQkJCQkJCTwvdGQ+DQoJCQkJCQk8L3RyPg0KCQkJCQkJDQoJCQkJCQk8dHI+DQoJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQk8cD5CZW5pZmljaWFyeSBBY2NvdW50IE51bWJlcjwvcD4NCgkJCQkJCQk8L3RkPg0KCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7YmVuaWZpY2lhcnlBY2NvdW50TnVtYmVyfSI+PC9wPg0KCQkJCQkJCTwvdGQ+DQoJCQkJCQk8L3RyPg0KCQkJCQkJPHRyPg0KCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJPHA+QmFuayBJRlNDIENvZGU8L3A+DQoJCQkJCQkJPC90ZD4NCgkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCTxwIHRoOnV0ZXh0PSIke2JhbmtJRlNDQ29kZX0iPjwvcD4NCgkJCQkJCQk8L3RkPg0KDQoJCQkJCQk8L3RyPg0KCQkJCQk8L3Rib2R5Pg0KCQkJCTwvdGFibGU+DQoJCQkJPGJyLz4NCgkJCTwvZGl2PiANCjwvYm9keT4NCg0KPC9odG1sPg==
                    status: INACTIVE
                    tupe: MINI STATEMENT
                    id: 628b337faa5ac729c76eee90
        "400":
          description: Please enter valid template details & content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              examples:
                Invalid Template:
                  description: Invalid Template
                  value:
                    status: BAD_REQUEST
                    timestamp: 23-05-2022 02:14:13
                    message: Please Enter Valid Template!
                    debugMessage: null
                    subErrors:
                      - object: template
                        field: name
                        rejectedValue: NotBlank
                        message: Template name is mandatory
                      - object: template
                        field: appId
                        rejectedValue: NotBlank
                        message: Application id is mandatory
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              examples:
                Internal server error:
                  description: Internal server error
                  value:
                    status: INTERNAL_SERVER_ERROR
                    timestamp: 23-05-2022 01:45:48
                    message: Something Went Wrong
                    debugMessage: null
                    subErrors: null
  /api/v1/templates/{templateId}:
    get:
      tags:
        - Templates
      description: Get template based on aapId and templateId.
      operationId: Template_4
      parameters:
        - name: templateId
          in: path
          required: true
          schema:
            type: string
        - name: appId
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Templates
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
              examples:
                Get Template by templateId and appId:
                  description: Get Template by templateId and appId
                  value:
                    appId: "0123"
                    name: Test
                    templateContent:
                      contentType: BASE64
                      data: PCFET0NUWVBFIGh0bWwNCglQVUJMSUMgIi0vL1czQy8vRFREIFhIVE1MIDEuMCBUcmFuc2l0aW9uYWwvL0VOIiAiaHR0cDovL3d3dy53My5vcmcvVFIveGh0bWwxL0RURC94aHRtbDEtdHJhbnNpdGlvbmFsLmR0ZCI+DQo8aHRtbCB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94aHRtbCINCgl4bWxuczp0aD0iaHR0cDovL3d3dy50aHltZWxlYWYub3JnIg0KCXhtbG5zOmxheW91dD0iaHR0cDovL3d3dy51bHRyYXEubmV0Lm56L3RoeW1lbGVhZi9sYXlvdXQiPg0KDQo8aGVhZD4NCjx0aXRsZT5UcmFuc2FjdGlvbiBSZWNlaXB0PC90aXRsZT4NCjxsaW5rIGhyZWY9J2h0dHA6Ly9mb250cy5nb29nbGVhcGlzLmNvbS9jc3M/ZmFtaWx5PVJvYm90bycNCglyZWw9J3N0eWxlc2hlZXQnIHR5cGU9J3RleHQvY3NzJyAvPg0KDQo8c3R5bGU+DQp0YWJsZSB7DQoJcGFkZGluZzogM3B4IDZweCAzcHggNnB4ICFpbXBvcnRhbnQ7DQp9DQoNCmJvZHkgew0KCWZvbnQtZmFtaWx5OiAnQ2FsaWJyaScsIHNhbnMtc2VyaWY7DQp9DQoNCnRyIHsNCglwYWRkaW5nOiA1cHggMHB4IDVweCAwcHggIWltcG9ydGFudDsNCgltYXJnaW46IDVweCAwcHggNXB4IDBweCAhaW1wb3J0YW50Ow0KCS8qb3V0bGluZTogdGhpbiBzb2xpZDsqLw0KfQ0KDQp0ZCB7DQoJcGFkZGluZzogMHB4IDBweCAwcHggMHB4ICFpbXBvcnRhbnQ7DQoJbWFyZ2luOiAwcHggMHB4IDBweCAwcHggIWltcG9ydGFudDsNCgkvKmJvcmRlci1yaWdodDogMXB4IHNvbGlkIGJsYWNrOyovDQp9DQoNCmgyIHsNCglwYWRkaW5nOiA1cHggMHB4IDVweCAwcHggIWltcG9ydGFudDsNCgltYXJnaW46IDVweCAwcHggNXB4IDBweCAhaW1wb3J0YW50Ow0KfQ0KDQpoNCB7DQoJcGFkZGluZzogNXB4IDJweCAycHggNXB4ICFpbXBvcnRhbnQ7DQoJbWFyZ2luOiA1cHggMnB4IDJweCA1cHggIWltcG9ydGFudDsNCgljb2xvcjogIzMzMzMzMyAhaW1wb3J0YW50Ow0KCWZvbnQtc2l6ZTogMThweCAhaW1wb3J0YW50Ow0KfQ0KDQpzdHJvbmcgew0KCXBhZGRpbmc6IDVweCAwcHggMTBweCA1cHggIWltcG9ydGFudDsNCgltYXJnaW46IDVweCAwcHggMnB4IDVweCAhaW1wb3J0YW50Ow0KCWNvbG9yOiAjMzMzMzMzICFpbXBvcnRhbnQ7DQoJZm9udC1zaXplOiAxNnB4ICFpbXBvcnRhbnQ7DQp9DQoNCnAgew0KCXBhZGRpbmc6IDJweCA2cHggMnB4IDZweCAhaW1wb3J0YW50Ow0KCW1hcmdpbjogMnB4IDZweCAycHggNnB4ICFpbXBvcnRhbnQ7DQp9DQoNCmhyIHsNCglib3JkZXI6IDAuNXB4IHNvbGlkICM4RTkwOTA7DQoJbWFyZ2luOiA1cHggMHB4IDVweCAwcHggIWltcG9ydGFudDsNCn0NCg0KLnVzZXItaW1hZ2Ugew0KCXdpZHRoOiAxMDBweCAhaW1wb3J0YW50Ow0KCWhlaWdodDogMTAwcHggIWltcG9ydGFudDsNCglib3JkZXI6IDJweCBzb2xpZCAjQkZDMkM0ICFpbXBvcnRhbnQ7DQoJYm9yZGVyLWNvbGxhcHNlOiBzZXBhcmF0ZSAhaW1wb3J0YW50Ow0KCXBlcnNwZWN0aXZlOiAxcHggIWltcG9ydGFudDsNCglvdmVyZmxvdzogaGlkZGVuICFpbXBvcnRhbnQ7DQp9DQo8L3N0eWxlPg0KPC9oZWFkPg0KDQo8Ym9keSBzdHlsZT0id2lkdGg6IDUwJTsiPg0KCTxkaXY+DQoNCgkJPHRhYmxlIHdpZHRoPSIxMDAlIj4NCgkJCTx0Ym9keT4NCgkJCQk8dHI+DQoJCQkJCTx0ZCB3aWR0aD0iMjAlIj48aW1nIHNyYz0iaHR0cHM6Ly9wYXluZWFyYnkuaW4vd3AtY29udGVudC90aGVtZXMvcGF5bmVhcmJ5L2Fzc2V0cy9pbWFnZXMvbG9nby5wbmciIHdpZHRoPSI5MCINCgkJCQkJCWhlaWdodD0iMzUiIHN0eWxlPSJtYXJnaW4tbGVmdDogMjBweDsiIGFsdD0iIj48L3RkPg0KCQkJCQk8dGQgd2lkdGg9IjgwJSI+PGgyPlRyYW5zYWN0aW9uIFJlY2VpcHQ8L2gyPjwvdGQ+DQoJCQkJPC90cj4NCgkJCTwvdGJvZHk+DQoJCTwvdGFibGU+DQoJCTxici8+DQoJPC9kaXY+DQoJDQoJIDxkaXY+DQoNCgkJCQk8dGFibGUgd2lkdGg9IjEwMCUiPg0KCQkJCQk8dGJvZHk+DQoJCQkJCQk8dHI+DQoJCQkJCQkJPHRkIGNvbHNwYW49IjIiPg0KCQkJCQkJCQk8aDQ+Q3VzdG9tZXIgRGV0YWlsczo8L2g0Pg0KCQkJCQkJCTwvdGQ+DQoNCgkJCQkJCTwvdHI+DQoJCQkJCQk8dHI+DQoJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQk8cD5Nb2JpbGUgTnVtYmVyIChTTVMpPC9wPg0KCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQk8cCB0aDp1dGV4dD0iJHtjdXN0b21lck1vYmlsZX0iPjwvcD4NCgkJCQkJCQk8L3RkPg0KCQkJCQkJPC90cj4NCgkJCQkJCTx0cj4NCgkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCTxwPkN1c3RvbWVyIE5hbWU8L3A+DQoJCQkJCQkJPC90ZD4NCgkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCTxwIHRoOnV0ZXh0PSIke2N1c3RvbWVyTmFtZX0iPjwvcD4NCgkJCQkJCQk8L3RkPg0KCQkJCQkJPC90cj4NCgkJCQkJPC90Ym9keT4NCgkJCQk8L3RhYmxlPg0KCQkJCTxici8+DQoJCQk8L2Rpdj4gPGJyLz4NCgkJCQk8ZGl2Pg0KCQkJCQk8dGFibGUgd2lkdGg9IjEwMCUiPg0KCQkJCQkJPHRib2R5Pg0KCQkJCQkJCTx0cj4NCgkJCQkJCQkJPHRkIGNvbHNwYW49IjIiPg0KCQkJCQkJCQkJPGg0PlRyYW5zYWN0aW9uIERldGFpbHM6PC9oND4NCgkJCQkJCQkJPC90ZD4NCgkJCQkJCQk8L3RyPg0KCQkJCQkJCTx0cj4NCgkJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQkJPHA+VHJhbnNhY3Rpb24gU3RhdHVzPC9wPg0KCQkJCQkJCQk8L3RkPg0KCQkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCQk8cCB0aDp1dGV4dD0iJHt0cmFuc2FjdGlvblN0YXR1c30iPjwvcD4NCgkJCQkJCQkJPC90ZD4NCgkJCQkJCQk8L3RyPg0KCQkJCQkJCTx0cj4NCgkJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQkJPHA+VHJhbnNhY3Rpb24gSUQ8L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwIHRoOnV0ZXh0PSIke3RyYW5zYWN0aW9uSUR9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCgkJCQkJCQk8dHI+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwPlRyYW5zYWN0aW9uIERhdGUgJiBUaW1lPC9wPg0KCQkJCQkJCQk8L3RkPg0KCQkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCQk8cCB0aDp1dGV4dD0iJHt0aW1lU3RhbXB9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCgkJCQkJCQk8dHI+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwPlBheW1lbnQgTWV0aG9kPC9wPg0KCQkJCQkJCQk8L3RkPg0KCQkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCQk8cCB0aDp1dGV4dD0iJHtwYXltZW50TWV0aG9kfSI+PC9wPg0KCQkJCQkJCQk8L3RkPg0KCQkJCQkJCTwvdHI+DQoJCQkJCQkJPHRyPg0KCQkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCQk8cD5UcmFuc2FjdGlvbiBNb2RlPC9wPg0KCQkJCQkJCQk8L3RkPg0KCQkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCQk8cCB0aDp1dGV4dD0iJHt0cmFuc2FjdGlvbk1vZGV9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCgkJCQkJCQk8dHI+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwPlRyYW5zYWN0aW9uIEFtb3VudDwvcD4NCgkJCQkJCQkJPC90ZD4NCgkJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7dHJhbnNhY3Rpb25BbW91bnR9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCgkJCQkJCQk8dHI+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwPkNvbnZlbmllbmNlIEZlZTwvcD4NCgkJCQkJCQkJPC90ZD4NCgkJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7Y29udmVuaWVuY2VGZWV9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCgkJCQkJCQk8dHI+DQoJCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJCTxwPlRvdGFsIEFtb3VudDwvcD4NCgkJCQkJCQkJPC90ZD4NCgkJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7dG90YWxBbW91bnR9Ij48L3A+DQoJCQkJCQkJCTwvdGQ+DQoJCQkJCQkJPC90cj4NCg0KCQkJCQkJPC90Ym9keT4NCgkJCQkJPC90YWJsZT4NCgkJCQk8L2Rpdj48YnIvPg0KCQkJCTxkaXY+DQoNCgkJCQk8dGFibGUgd2lkdGg9IjEwMCUiPg0KCQkJCQk8dGJvZHk+DQoJCQkJCQk8dHI+DQoJCQkJCQkJPHRkIGNvbHNwYW49IjIiPg0KCQkJCQkJCQk8aDQ+QmVuaWZpY2lhcnkgRGV0YWlsczo8L2g0Pg0KCQkJCQkJCTwvdGQ+DQoNCgkJCQkJCTwvdHI+DQoJCQkJCQk8dHI+DQoJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQk8cD5CZW5pZmljaWFyeSBOYW1lIDwvcD4NCgkJCQkJCQk8L3RkPg0KCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7YmVuaWZpY2lhcnlOYW1lfSI+PC9wPg0KCQkJCQkJCTwvdGQ+DQoJCQkJCQk8L3RyPg0KCQkJCQkJPHRyPg0KCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJPHA+QmVuaWZpY2lhcnkgQmFuazwvcD4NCgkJCQkJCQk8L3RkPg0KCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7YmVuaWZpY2lhcnlCYW5rfSI+PC9wPg0KCQkJCQkJCTwvdGQ+DQoJCQkJCQk8L3RyPg0KCQkJCQkJDQoJCQkJCQk8dHI+DQoJCQkJCQkJPHRkIHdpZHRoPSI1MCUiPg0KCQkJCQkJCQk8cD5CZW5pZmljaWFyeSBBY2NvdW50IE51bWJlcjwvcD4NCgkJCQkJCQk8L3RkPg0KCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJPHAgdGg6dXRleHQ9IiR7YmVuaWZpY2lhcnlBY2NvdW50TnVtYmVyfSI+PC9wPg0KCQkJCQkJCTwvdGQ+DQoJCQkJCQk8L3RyPg0KCQkJCQkJPHRyPg0KCQkJCQkJCTx0ZCB3aWR0aD0iNTAlIj4NCgkJCQkJCQkJPHA+QmFuayBJRlNDIENvZGU8L3A+DQoJCQkJCQkJPC90ZD4NCgkJCQkJCQk8dGQgd2lkdGg9IjUwJSI+DQoJCQkJCQkJCTxwIHRoOnV0ZXh0PSIke2JhbmtJRlNDQ29kZX0iPjwvcD4NCgkJCQkJCQk8L3RkPg0KDQoJCQkJCQk8L3RyPg0KCQkJCQk8L3Rib2R5Pg0KCQkJCTwvdGFibGU+DQoJCQkJPGJyLz4NCgkJCTwvZGl2PiANCjwvYm9keT4NCg0KPC9odG1sPg==
                    status: ACTIVE
                    type: MINI STATEMENT
                    id: 628b42b31c9bc37e1cd3338b
                    tag: INVOICE
                    createdDate: 2022-05-23 13:45:47
                    lastModifiedDate: 2022-05-23 13:45:47
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              examples:
                Unauthorized:
                  description: Unauthorized
                  value:
                    status: UNAUTHORIZED
                    timestamp: 23-05-2022 02:03:26
                    message: UNAUTHORIZED
                    debugMessage: null
                    subErrors: null
        "400":
          description: Please enter valid templateId & AppId
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              examples:
                Invalid request:
                  description: Invalid request
                  value:
                    status: NOT_FOUND
                    timestamp: 23-05-2022 03:07:01
                    message: Template not present
                    debugMessage: null
                    subErrors: null
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              examples:
                Internal server error:
                  description: Internal server error
                  value:
                    status: INTERNAL_SERVER_ERROR
                    timestamp: 23-05-2022 01:45:48
                    message: Something Went Wrong
                    debugMessage: null
                    subErrors: null
components:
  schemas:
    DocumentContent:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    DocumentDetails:
      type: object
      properties:
        documentContent:
          type: array
          items:
            $ref: '#/components/schemas/DocumentContent'
    Template:
      type: object
      properties:
        appId:
          type: string
        name:
          type: string
        templateContent:
          $ref: '#/components/schemas/TemplateContent'
        status:
          type: string
          enum:
            - ACTIVE
            - INACTIVE
        id:
          type: string
        type:
          type: string
        tag:
          type: string
          enum:
            - INVOICE
            - ORDER
        createdDate:
          type: string
          format: date-time
        lastModifiedDate:
          type: string
          format: date-time
    TemplateContent:
      required:
        - contentType
        - data
      type: object
      properties:
        contentType:
          type: string
          enum:
            - BASE64
        data:
          type: string
    ApiError:
      type: object
      properties:
        status:
          type: string
          enum:
            - 100 CONTINUE
            - 101 SWITCHING_PROTOCOLS
            - 102 PROCESSING
            - 103 CHECKPOINT
            - 200 OK
            - 201 CREATED
            - 202 ACCEPTED
            - 203 NON_AUTHORITATIVE_INFORMATION
            - 204 NO_CONTENT
            - 205 RESET_CONTENT
            - 206 PARTIAL_CONTENT
            - 207 MULTI_STATUS
            - 208 ALREADY_REPORTED
            - 226 IM_USED
            - 300 MULTIPLE_CHOICES
            - 301 MOVED_PERMANENTLY
            - 302 FOUND
            - 302 MOVED_TEMPORARILY
            - 303 SEE_OTHER
            - 304 NOT_MODIFIED
            - 305 USE_PROXY
            - 307 TEMPORARY_REDIRECT
            - 308 PERMANENT_REDIRECT
            - 400 BAD_REQUEST
            - 401 UNAUTHORIZED
            - 402 PAYMENT_REQUIRED
            - 403 FORBIDDEN
            - 404 NOT_FOUND
            - 405 METHOD_NOT_ALLOWED
            - 406 NOT_ACCEPTABLE
            - 407 PROXY_AUTHENTICATION_REQUIRED
            - 408 REQUEST_TIMEOUT
            - 409 CONFLICT
            - 410 GONE
            - 411 LENGTH_REQUIRED
            - 412 PRECONDITION_FAILED
            - 413 PAYLOAD_TOO_LARGE
            - 413 REQUEST_ENTITY_TOO_LARGE
            - 414 URI_TOO_LONG
            - 414 REQUEST_URI_TOO_LONG
            - 415 UNSUPPORTED_MEDIA_TYPE
            - 416 REQUESTED_RANGE_NOT_SATISFIABLE
            - 417 EXPECTATION_FAILED
            - 418 I_AM_A_TEAPOT
            - 419 INSUFFICIENT_SPACE_ON_RESOURCE
            - 420 METHOD_FAILURE
            - 421 DESTINATION_LOCKED
            - 422 UNPROCESSABLE_ENTITY
            - 423 LOCKED
            - 424 FAILED_DEPENDENCY
            - 425 TOO_EARLY
            - 426 UPGRADE_REQUIRED
            - 428 PRECONDITION_REQUIRED
            - 429 TOO_MANY_REQUESTS
            - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
            - 451 UNAVAILABLE_FOR_LEGAL_REASONS
            - 500 INTERNAL_SERVER_ERROR
            - 501 NOT_IMPLEMENTED
            - 502 BAD_GATEWAY
            - 503 SERVICE_UNAVAILABLE
            - 504 GATEWAY_TIMEOUT
            - 505 HTTP_VERSION_NOT_SUPPORTED
            - 506 VARIANT_ALSO_NEGOTIATES
            - 507 INSUFFICIENT_STORAGE
            - 508 LOOP_DETECTED
            - 509 BANDWIDTH_LIMIT_EXCEEDED
            - 510 NOT_EXTENDED
            - 511 NETWORK_AUTHENTICATION_REQUIRED
        timestamp:
          type: string
          format: date-time
        message:
          type: string
        debugMessage:
          type: string
        subErrors:
          type: array
          items:
            $ref: '#/components/schemas/ApiSubError'
    ApiSubError:
      type: object
      properties:
        object:
          type: string
        field:
          type: string
        rejectedValue:
          type: object
        message:
          type: string
